### ISSUE TITLE
isoft.nginx didn't work with ansible 1.4

### ISSUE THREAD

**Issue by benbor** [intellectsoft-uk/ansible-roles#4]
Current variant
```
- name: Ensuredisable_default_pool php-fpm is started and enabled at boot (if configured).
  service:
    name: php5-fpm
    state: started
    enabled: yes
```
It's work for me :
```
- name: Ensuredisable_default_pool php-fpm is started and enabled at boot (if configured).
  service:
    name: php5-fpm
    state: started

```
